[package]
name = "otlp2parquet-batch"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
otlp2parquet-core = { path = "../otlp2parquet-core" }
otlp2parquet-proto = { path = "../otlp2parquet-proto" }

# Batching dependencies
parquet = { workspace = true }
parking_lot = { workspace = true }
blake3 = { workspace = true }

# Protocol
prost = { workspace = true }

# Utilities
anyhow = { workspace = true }

[target.'cfg(target_arch = "wasm32")'.dependencies]
parquet = { workspace = true, features = ["arrow", "snap"] }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
parquet = { workspace = true, features = ["arrow", "snap", "zstd"] }
